### ISSUE TITLE
FDA Incident Drug Search

### ISSUE THREAD

**Issue by kathyyun** [akulasainath/18frepo#1]
**User Story**
As a user, I want to search for drugs so that I may find information on FDA incident reports related to those particular drugs.

**Acceptance Criteria**
- User can enter a single drug
- User can enter multiple drugs
- System suggests drug names based on the "medicinal product" on incident reports 
- System suggests drug names once an entire search criteria word matches a word in medicinal products found in incident reports

**Comment by akulasainath** [comment]
Assigning to myself

**Comment by akulasainath** [comment]
accidentally closed this issue, reopening it,

**Comment by ghost** [comment]
Modifying user title to reflect entire search term matches drug names

**Comment by ghost** [comment]
Updating **User Story**

**Comment by ghost** [comment]
Modifying **User Story**:
- Original Story: _As a user, I want the system to suggest drug names based on search words I have entered so that I can accurately find drugs._
- Updated User Story: _As a user, I want to search for drugs so that I may find information on FDA incident reports related to those particular drugs._
- **Update reason:** User story modified as a result of 6/22 demo

**Comment by ghost** [comment]
**Demo Feedback:**
- Add "Max. 5 drugs" message next to _Selected Drugs_ section
- Update check mark symbol next to search field to "Go"
- Update "Other Filters" to "Filter Incidents by:"
- Update "Outcome:" to "Incident Outcome:"
- Update "Country:" to "Incident Location:"
- Update "Gender:" to "Patient Gender:"

**Update reason:** Feedback incorporated as a result of an app demo on 6/24.

**Comment by ghost** [comment]
Status updated from _In Progress_ to _Testing_

**Comment by ghost** [comment]
PO testing complete. Status changed from _Testing_ to _Done_.
