### ISSUE TITLE
Filter results by incident with a "serious" result/condition

### ISSUE THREAD

**Issue by thartsel** [akulasainath/18frepo#11]
**User Story**
As a user, I want the option to view reaction results by incidents where the incident outcome is serious so that I can narrow the scope of my results.

**Comment by ghost** [comment]
Updating issue title to indicate change from a sort functionality to filter functionality.

**Comment by msahniventera** [comment]
Filter results by incident patient weight

**Comment by ghost** [comment]
Updated user story to reflect change from a sort functionality to filter functionality.

**Comment by ghost** [comment]
Modifying **User Story** and title:
- Original User Story:
  - _As a user, I want the option to view reaction results by incidents where only a drug is suspected as a contributor so that I can narrow the scope of my results._
- New User Story:
  - _As a user, I want the option to view reaction results by incidents where the incident outcome is serious so that I can narrow the scope of my results._
- **Note:** Serious = The adverse event resulted in death, a life threatening condition, hospitalization, disability, congenital anomali, or other serious condition.
- **Issue Update Reason:** Original user story was based on initial assumptions of the API and required modification as additional research into the API and its queries was conducted.

**Comment by ghost** [comment]
Status updated from _Ice Box_ to _In Progress_.

**Comment by ghost** [comment]
Status updated from _In Progress_ to _Testing_.

**Comment by ghost** [comment]
PO testing complete. Status changed from _Testing_ to _Done_.
