### ISSUE TITLE
Identify and finalize technologies to support continuous monitoring of the product.

### ISSUE THREAD

**Issue by ncrismali** [akulasainath/18frepo#25]
Set up continuous monitoring technologies.

**Comment by ghost** [comment]
Description udpdated

**Comment by dfitch-ventera** [comment]
CloudAware is being used to continuously monitor the security posture and situation awareness of the application hosted at AWS as part of the overall effort to manage application and organizational risk.  CloudAware's FedRAMP Continuous Monitoring Module would typically be used alongside GSA's other existing security tools to provide data needed to continuously monitor the AWS hosted application. 

Amazon Web Services (AWS) CloudWatch monitoring is configured to monitor the Test and Production Servers and Load Balancers for the application.  Auto-scale groups are configured based on CloudWatch alarms so that if CPU utilization (as monitored by CloudWatch) surpasses 80% for more than 5 minutes on a server, a new instance of the server will be started to help with the load.  Alarms for load balancer latency and HTTP errors are also configured in CloudWatch.

**Comment by dfitch-ventera** [comment]
Ryan set up internal monitoring on the servers to monitor Apache services, etc. and restart them if they are down.

**Comment by thartsel** [comment]
Evidence related to the use of CloudAware, CloudWatch, and Modit can be found here:

https://github.com/akulasainath/18frepo/blob/master/18F%20Evidence/Continuous%20Monitoring%20Evidence/Continuous%20Monitoring%20Evidence.docx
