### ISSUE TITLE
Re-organized search file structure

### ISSUE THREAD

**Issue by thartsel** [akulasainath/18frepo#3]

**Comment by ghost** [comment]
**User Story** removed:
- Original: _As a person who was prescribed drugs, I want to be able to enter the drugs that I take to find out what negative reactions have been reported to the FDA by other people taking the drugs so that I can be aware of what to expect._

**Update reason:** Altered as duplicate of #1

**Comment by thartsel** [comment]
Closing because this was a duplicate of #1
